### ISSUE TITLE
Galarian Pokemons not in the database.

### ISSUE THREAD

**Issue by oozanyuksel** [CHamburr/PokeAssistant#5]
**Describe the bug**
Galarian Pokemons are not in the database.

**To Reproduce**
1. A galarian pokemon appears 
2. The bot replies
`Pokemon Not Found
Please contact the owner CHamburr#2591 to add this Pokemon to the database.`

**Expected behavior**
The bot should find and tell which galarian pokemon is this.

**Screenshots**
https://i.imgur.com/EnXog6I.png

**Desktop (please complete the following information):**
- Not necessary

**Smartphone (please complete the following information):**
 - Not necessary

**Additional context**
Here is a link to Galarian  Farfetch'd:
https://cdn.discordapp.com/attachments/696045851549892618/696155383433003028/PokecordSpawn.jpg

**Comment by ObliviousDonkey** [comment]
Use this one
[Pokemons.txt](https://github.com/CHamburr/PokeAssistant/files/4473819/Pokemons.txt)

**Comment by oozanyuksel** [comment]
Thank you
